version: '3'
services:
  app:
    image: vps-value-tracker
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs
    environment:
      - DOMAIN=${DOMAIN}
      - FIXER_API_KEY=${FIXER_API_KEY}
    restart: unless-stopped 