version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: vps-tracker-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: vps-tracker-backend
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/vps-tracker
      - JWT_SECRET=${JWT_SECRET}
      - FIXER_API_KEY=${FIXER_API_KEY}
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vps-tracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data: 