version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: vps-tracker-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin123456}
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - vps-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: vps-tracker-backend
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-admin123456}@mongodb:27017/vps-tracker?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - FIXER_API_KEY=${FIXER_API_KEY}
    depends_on:
      - mongodb
    ports:
      - "80:3000"
    volumes:
      - ./backend/configs:/app/configs
    networks:
      - vps-network

networks:
  vps-network:
    driver: bridge

volumes:
  mongodb_data: 