version: '3.8'

services:
  app:
    image: kpowered/vps-value-tracker:latest
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./data:/app/prisma/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 