version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/vps-tracker
      - JWT_SECRET=your-secret-key
      - FIXER_API_KEY=e65a0dbfc190ce964f2771bca5c08e13
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 