server:
  port: 3000
  host: "0.0.0.0"

mongodb:
  uri: "mongodb://localhost:27017/vps-tracker"

jwt:
  secret: "your-secret-key"
  expiry: "24h"

fixer:
  api_key: "e65a0dbfc190ce964f2771bca5c08e13"
  base_url: "http://data.fixer.io/api" 